import json
import os
from typing import Any

import anthropic
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import sources
from prompts import OUTPUT_SCHEMA, SYSTEM_PROMPT, build_user_prompt

load_dotenv()

# Override with MODEL=... in .env if you want a different tier.
# claude-opus-5 gives deeper analysis; claude-haiku-4-5-20251001 is fastest.
MODEL = os.environ.get("MODEL", "claude-sonnet-5")

# Raised again for the JSON contract. The response now quotes real C++ twice --
# once as old_str and once as new_str -- and a truncated response is worse here
# than it was under the markdown format: markdown degraded to a short answer,
# whereas truncated JSON does not parse at all, so every token of the diagnosis
# is lost along with the patch. 8000 leaves room for a function-sized edit.
MAX_TOKENS = int(os.environ.get("MAX_TOKENS", "8000"))

app = FastAPI(title="Vampire-Core AI Profiler", version="0.4.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:4173"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# AsyncAnthropic, not Anthropic: the sync client blocks the event loop for the
# whole model call, which would stall every other request on this worker.
_client: anthropic.AsyncAnthropic | None = None


def get_client() -> anthropic.AsyncAnthropic:
    global _client
    if _client is None:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise HTTPException(
                status_code=500,
                detail="ANTHROPIC_API_KEY not set. Put it in server/.env or export it.",
            )
        _client = anthropic.AsyncAnthropic(api_key=api_key)
    return _client


class OptimizeRequest(BaseModel):
    fps: float
    frameTimeMs: float
    entityCount: int
    collisionMode: str
    memoryMode: str
    codeSnippet: str

    # Both optional, so a client built against v0.1.0 still works unchanged.
    #
    # telemetry is typed as a bare dict rather than a mirrored pydantic model on
    # purpose. The producing schema lives in web/src/logging/PerfLogger.ts and
    # will keep growing fields; a strict model here would turn every frontend
    # addition into a 422 at exactly the wrong moment, and the formatter reads
    # the payload defensively with .get() anyway. The cost of being wrong is a
    # blank column in a table, not a corrupted analysis.
    telemetry: dict[str, Any] | None = None
    auraSnippet: str | None = None

    # Not validated against an enum here, unlike the recommendation parser
    # below. That parser guards a value that gets fed back into embind, where a
    # bad string is a crash; this one only ever reaches a prompt, where the
    # worst case is a mislabelled column. Rejecting the request outright would
    # mean a frontend that adds a third distribution breaks the endpoint before
    # anyone can see what it sent.
    spawnDistribution: str | None = None


class Recommendation(BaseModel):
    """The configuration the model says should be running.

    This exists so the demo can act on the verdict -- swap the running
    collision/memory mode, or load a pre-built wasm variant -- without a human
    reading the prose. Every field stays optional even though the schema marks
    them required: the schema constrains what the model emits, and this type
    describes what the SERVER is willing to vouch for. A value that fails the
    enum check below is dropped to None rather than passed through, because a
    wrong mode swap is worse than no recommendation.
    """

    collision:  str | None = None
    memory:     str | None = None
    confidence: str | None = None
    reason:     str | None = None


class Patch(BaseModel):
    """A proposed edit, after the server has checked it against the file.

    `applies` is the field to branch on, and it is deliberately not the same
    thing as "the model returned a patch". A response can contain a confident,
    well-argued edit whose old_str was retyped from memory instead of quoted,
    and that edit is worthless -- but it is worthless in a way only the server
    can detect. Reporting it as a failed patch with the reason attached is more
    useful to the demo than either applying it or hiding it.
    """

    file:        str
    symbol:      str
    rationale:   str
    applies:     bool
    reason:      str
    # Unified diff generated by the SERVER from the verified replacement, so its
    # line numbers are computed against the real file rather than recalled by a
    # model. Empty when the patch does not apply.
    diff:        str = ""
    startLine:   int = 0
    occurrences: int = 0


class OptimizeResponse(BaseModel):
    # Markdown rendered by the server FROM the JSON, kept so the existing
    # frontend <pre> keeps showing something readable without a change. The
    # structured fields below are the contract; this is a view of them.
    analysis: str
    model: str

    diagnosis: str = ""
    evidence: list[str] = []
    expectedImpact: str = ""
    patch: Patch | None = None
    recommendation: Recommendation | None = None
    telemetrySamples: int = 0

    # What the server actually read off disk, as 'path:start-end'. Reported
    # rather than assumed: extraction can come back empty (no repo mounted, a
    # renamed symbol) and the request still succeeds on the client's paraphrase,
    # so a caller needs to be able to tell the two apart. An empty list means
    # the analysis was written against the illustrative snippet.
    sourceFiles: list[str] = []


_VALID_COLLISION = {"bruteforce": "BruteForce", "quadtree": "QuadTree"}
_VALID_MEMORY = {"aos": "AoS", "soa": "SoA"}
_VALID_CONFIDENCE = {"high", "medium", "low"}


def parse_recommendation(block: Any) -> Recommendation | None:
    """Validate the recommendation object against the enums the engine accepts.

    The output schema already constrains these with `enum`, so this looks like
    belt and braces. It is not: the schema governs what the model may emit, and
    this governs what the server is willing to hand to embind, where an
    unrecognised mode string is a wasm crash that reads like an engine bug
    rather than a malformed response. Cheap check, expensive failure, and the
    two live in different systems -- so both.
    """
    if not isinstance(block, dict):
        return None

    rec = Recommendation()
    rec.collision = _VALID_COLLISION.get(str(block.get("collision", "")).lower())
    rec.memory    = _VALID_MEMORY.get(str(block.get("memory", "")).lower())
    conf          = str(block.get("confidence", "")).lower()
    rec.confidence = conf if conf in _VALID_CONFIDENCE else None
    reason        = block.get("reason")
    rec.reason    = str(reason)[:200] if reason else None

    if rec.collision is None and rec.memory is None:
        return None
    return rec


def build_patch(block: Any, collision_mode: str, memory_mode: str) -> Patch | None:
    """Verify a proposed edit against the file it claims to edit.

    Returns None only when the model declined to propose one. A patch that was
    proposed and failed verification comes back with applies=False and the
    reason, because "the optimizer suggested an edit that does not apply" is
    information the demo should show rather than swallow.
    """
    if not isinstance(block, dict):
        return None

    file    = str(block.get("file") or "")
    symbol  = str(block.get("symbol") or "")
    old_str = str(block.get("old_str") or "")
    new_str = str(block.get("new_str") or "")

    v = sources.verify_patch(file, old_str, new_str, symbol=symbol,
                             collision_mode=collision_mode, memory_mode=memory_mode)
    return Patch(
        file=file, symbol=symbol,
        rationale=str(block.get("rationale") or ""),
        applies=v.applies, reason=v.reason, diff=v.diff,
        startLine=v.start_line, occurrences=v.occurrences,
    )


def render_markdown(data: dict[str, Any], patch: Patch | None) -> str:
    """Render the JSON back into the markdown the frontend already displays.

    The structured fields are the real contract; this exists so that switching
    the model's output format is not also a frontend change. It renders the
    SERVER's diff rather than the model's new_str, so what a reader sees is what
    was actually verified.
    """
    out: list[str] = []
    if data.get("diagnosis"):
        out.append("## Bottleneck Diagnosis\n" + str(data["diagnosis"]))

    ev = [str(e) for e in (data.get("evidence") or [])]
    if ev:
        out.append("## Evidence\n" + "\n".join(f"- {e}" for e in ev))

    if patch is not None:
        head = f"## Proposed Patch\n`{patch.file}`"
        if patch.symbol:
            head += f" -- `{patch.symbol}`"
        if patch.startLine:
            head += f" (line {patch.startLine})"
        if patch.rationale:
            head += f"\n\n{patch.rationale}"
        if patch.applies:
            head += f"\n\n```diff\n{patch.diff}```"
        else:
            head += (f"\n\nNOT APPLIED -- {patch.reason}. The diagnosis above "
                     f"still stands; the edit does not.")
        out.append(head)

    if data.get("expected_impact"):
        out.append("## Expected Impact\n" + str(data["expected_impact"]))

    rec = data.get("recommendation") or {}
    if rec:
        out.append(
            "## Recommended Configuration\n"
            f"collision: {rec.get('collision', '?')}\n"
            f"memory: {rec.get('memory', '?')}\n"
            f"confidence: {rec.get('confidence', '?')}\n"
            f"reason: {rec.get('reason', '')}")
    return "\n\n".join(out)


@app.post("/api/optimize", response_model=OptimizeResponse)
async def optimize(req: OptimizeRequest) -> OptimizeResponse:
    client = get_client()
    samples = len((req.telemetry or {}).get("records") or [])

    # Real source beats the client's snippet, and failing to find it is not an
    # error: a request carrying thirty seconds of telemetry is still worth
    # answering from the paraphrase, with the prompt saying so plainly.
    chunks = sources.collect(req.collisionMode, req.memoryMode)
    bundle = sources.render(
        chunks, req.collisionMode, req.memoryMode, req.spawnDistribution or "Uniform"
    )
    try:
        message = await client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=SYSTEM_PROMPT,
            # Schema-enforced JSON rather than a prompt asking for JSON. The
            # difference matters for the patch: old_str has to survive the round
            # trip byte for byte, and a model writing free-form JSON inside a
            # markdown fence will sooner or later escape a backslash or wrap a
            # long line and silently break the anchor match.
            output_config={"format": {"type": "json_schema", "schema": OUTPUT_SCHEMA}},
            messages=[
                {
                    "role": "user",
                    "content": build_user_prompt(
                        req.fps,
                        req.frameTimeMs,
                        req.entityCount,
                        req.collisionMode,
                        req.memoryMode,
                        req.codeSnippet,
                        telemetry=req.telemetry,
                        aura_snippet=req.auraSnippet,
                        spawn_distribution=req.spawnDistribution or "Uniform",
                        source_bundle=bundle,
                    ),
                }
            ],
        )
        text = "".join(block.text for block in message.content if block.type == "text")

        # output_config.format guarantees valid JSON, so a failure here is an
        # infrastructure problem (a truncated response at max_tokens, a proxy
        # rewriting the body), not a model formatting slip. It gets its own
        # error rather than an empty analysis, because degrading silently to
        # "no recommendation" would make a broken deployment look like a
        # cautious optimizer.
        try:
            data = json.loads(text)
        except json.JSONDecodeError as e:
            raise HTTPException(
                status_code=502,
                detail=f"model returned unparseable JSON ({e}); "
                       f"stop_reason={getattr(message, 'stop_reason', 'unknown')}, "
                       f"{len(text)} chars. A stop_reason of max_tokens means "
                       f"MAX_TOKENS ({MAX_TOKENS}) is too low for this response.",
            )

        patch = build_patch(data.get("patch"), req.collisionMode, req.memoryMode)
        return OptimizeResponse(
            analysis=render_markdown(data, patch),
            model=MODEL,
            recommendation=parse_recommendation(data.get("recommendation")),
            telemetrySamples=samples,
            sourceFiles=sources.cited(chunks),
            diagnosis=str(data.get("diagnosis") or ""),
            evidence=[str(e) for e in (data.get("evidence") or [])],
            expectedImpact=str(data.get("expected_impact") or ""),
            patch=patch,
        )
    except anthropic.APIStatusError as e:
        raise HTTPException(status_code=502, detail=f"{e.status_code}: {e.message}")
    except anthropic.APIError as e:
        raise HTTPException(status_code=502, detail=str(e))


@app.get("/health")
async def health() -> dict:
    # core_readable is worth surfacing here rather than only failing quietly at
    # analysis time: "the profiler is up" and "the profiler can see the C++" are
    # different claims, and the second is the one that decides whether an answer
    # cites real line numbers.
    probe = sources.collect("QuadTree", "SoA")
    return {
        "status": "ok",
        "model": MODEL,
        "key_configured": bool(os.environ.get("ANTHROPIC_API_KEY")),
        "core_root": str(sources.CORE_ROOT),
        "core_readable": bool(probe),
        "source_regions": sources.cited(probe),
    }
